### PR TITLE
Its really anoying to have in the console!

### PR DESCRIPTION
**Pull request by EtchReborn**
Remove this right away or change it

### CODE REVIEW

**Comment by ivand-sykt** [comment]
this plugin is not finished
btw, it is debug info

**Comment by ivand-sykt** [comment]
if it is annoying, just delete this line of code :)

**Comment by EtchReborn** [comment]
I dont know what line i should delete ( i dont wanna break the plugin

**Comment by EtchReborn** [comment]
Tell me what line to delete so i dont break the plugin

**Comment by ivand-sykt** [comment]
@EtchReborn line with 'секунд'

**Comment by EtchReborn** [comment]
Okay thanks btw you should remove it here too or just do a config where you can enable or disable it

**Pull request closed without merging**
